functionsDirectory = "C:\\Blindsight\\netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "C:\\Blindsight\\web\\app"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run model && npm run build:web"
functions = "C:\\Blindsight\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"